---
- name: include role specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - create_vlan.yml #- "{{ vlan_resource }}.yml"
      paths:
        - "{{ playbook_dir }}/providers/{{ ansible_network_os }}"
        - "~/.ansible/network/network-vlans/providers/{{ ansible_network_os }}"
        - "/etc/ansible/network/network-vlans/providers/{{ ansible_network_os }}"
        - "{{ role_path }}/providers/{{ ansible_network_os }}"

#- include: check_vars.yml tags=vlans,vlans:check,check
#
#- name: Include task list in play only if the condition is true
#  include_tasks: "{{ provider }}.yml"
#  when: provider is defined
#
#- name: Include task list in play only if the condition is true
#  include_tasks: "{{ check_vars }}.yml"
#  when: check_vars is defined

